version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-backend-profile"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ysaomds52jgp"
s3_prefix = "demo-backend-profile"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
